### default supported ROS message types:
# sensor_msgs/Imu
# geometry_msgs/Twist
# std_msgs/String
# (modify/add in ros_sub_pub.hpp if you need more)
### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: "*" # '*' stands for all self IPs
  gcs1: 192.168.30.100
  gcs2: 194.194.194.180
  neighbor: 127.0.0.1 # modify to the IP of other machines

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
## 30xx  drone -> ground station
## 31xx  drone -> drone
## 32xx  ground station -> drone
send_topics:
  - topic_name: /drone_2_ego_planner_node/grid_map/occupancy
    msg_type: sensor_msgs/PointCloud2
    srcIP: self
    srcPort: 3001
    max_freq: 5

  - topic_name: /odom_2
    msg_type: nav_msgs/Odometry
    srcIP: self
    srcPort: 4001
    max_freq: 10

  - topic_name: /drone_2_ego_planner_node/optimal_list
    msg_type: visualization_msgs/Marker
    srcIP: self
    srcPort: 5001
    max_freq: 10
# TODO: send takeoff and land topic

####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
  - topic_name: /odom_new
    msg_type: nav_msgs/Odometry
    srcIP: gcs1
    srcPort: 6001